import { useEffect, useState, type ReactNode } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Heart, Leaf, Menu, Minus, Plus, Search, ShoppingBag, SlidersHorizontal, Sparkles, Star, Trash2, Truck, UserRound, X } from 'lucide-react'
import { Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useCart } from './context/CartContext'
import { useAuth } from './context/AuthContext'
import { catalogRepository } from './services/catalogRepository'
import type { CategorySlug, Product } from './types/catalog'
import { CheckoutPanel } from './components/CheckoutPanel'
import { AccountPage, ProfilePage } from './pages/AccountPages'
import { AdminPage } from './pages/AdminPage'
import { SHOP_CATEGORIES } from './data/categories'

const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })

function Shell({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const navigate = useNavigate()
  const { itemCount } = useCart()
  const { user } = useAuth()
  function search(event: React.FormEvent) {
    event.preventDefault()
    if (query.trim()) navigate(`/search?q=${encodeURIComponent(query.trim())}`)
  }
  const navigation = [{ to: '/shop', label: 'Shop' }, ...SHOP_CATEGORIES.map((category) => ({ to: `/shop?category=${category.slug}`, label: category.name })), { to: '/#story', label: 'Our story' }]
  return <>
    <header className="sticky top-0 z-50 border-b border-ink/8 bg-paper/92 backdrop-blur-xl">
      <div className="shell flex h-[76px] items-center justify-between gap-5">
        <Link className="font-display text-[28px] leading-none tracking-[-0.08em] text-forest" to="/">shop<span className="text-terracotta">x</span></Link>
        <nav className="hidden items-center gap-6 lg:flex">{navigation.map((item) => <NavLink className="nav-link" key={item.label} to={item.to}>{item.label}</NavLink>)}</nav>
        <form onSubmit={search} className="hidden w-full max-w-[310px] items-center rounded-full bg-sand px-4 md:flex">
          <Search size={16} className="text-ink/45" /><input aria-label="Search products" value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 w-full bg-transparent px-2 text-sm outline-none placeholder:text-ink/45" placeholder="Search thoughtful finds..." />
        </form>
        <div className="flex items-center gap-2"><Link aria-label="Account" className="icon-button hidden md:grid" to={user ? '/profile' : '/account?mode=login'}><UserRound size={19} /></Link><button aria-label="Open menu" onClick={() => setOpen(!open)} className="icon-button lg:hidden"><Menu size={20} /></button><Link aria-label="Cart" className="icon-button relative" to="/cart"><ShoppingBag size={19} />{itemCount > 0 && <span className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-terracotta px-1 text-[10px] font-bold text-white">{itemCount}</span>}</Link></div>
      </div>
      {open && <div className="shell border-t border-ink/8 py-4 lg:hidden"><form onSubmit={search} className="mb-4 flex items-center rounded-full bg-sand px-4"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 w-full bg-transparent px-2 text-sm outline-none" placeholder="Search products..." /></form><nav className="grid gap-3">{navigation.map((item) => <NavLink onClick={() => setOpen(false)} className="nav-link" key={item.label} to={item.to}>{item.label}</NavLink>)}</nav></div>}
    </header>
    <main>{children}</main>
    <footer className="mt-18 bg-forest text-white"><div className="shell grid gap-10 py-12 md:grid-cols-[1.4fr_1fr_1fr]"><div><div className="font-display text-4xl tracking-[-0.08em]">shop<span className="text-butter">x</span></div><p className="mt-4 max-w-sm text-sm leading-6 text-white/65">A more beautiful way to find the everyday things you need.</p></div><div><p className="footer-label">Explore</p><Link to="/shop" className="footer-link">Shop all</Link>{SHOP_CATEGORIES.map((category) => <Link key={category.slug} to={`/shop?category=${category.slug}`} className="footer-link">{category.name}</Link>)}<Link to="/cart" className="footer-link">Your bag</Link></div><div><p className="footer-label">Good to know</p><p className="text-sm leading-6 text-white/65">Secure checkout and delivery for the things you love.</p></div></div></footer>
  </>
}

function SectionTitle({ eyebrow, title, link }: { eyebrow?: string; title: ReactNode; link?: string }) {
  return <div className="mb-6 flex items-end justify-between gap-4"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="section-title">{title}</h2></div>{link && <Link className="under-link" to={link}>View all <ArrowRight size={15} /></Link>}</div>
}

function ProductCard({ product }: { product: Product }) {
  const { addItem } = useCart()
  return <article className="group overflow-hidden rounded-[18px] bg-white shadow-card"><Link className="relative block aspect-[.85] overflow-hidden bg-stone" to={`/products/${product.slug}`}><img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" />{product.badge && <span className="absolute left-3 top-3 rounded-full border border-white/70 bg-white/80 px-2.5 py-1 text-[10px] font-semibold text-forest backdrop-blur">{product.badge}</span>}<button aria-label={`Save ${product.name}`} className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-full bg-white/85 text-forest opacity-0 transition group-hover:opacity-100"><Heart size={15} /></button></Link><div className="p-3.5"><div className="mb-2 flex gap-1">{product.colors.map((color) => <span key={color} style={{ backgroundColor: color }} className="h-2.5 w-2.5 rounded-full ring-1 ring-black/5" />)}</div><Link to={`/products/${product.slug}`} className="line-clamp-1 text-sm font-semibold text-ink">{product.name}</Link><p className="mt-1 line-clamp-2 min-h-10 text-xs leading-5 text-ink/58">{product.description}</p><div className="mt-3 flex items-center justify-between gap-2"><div><span className="text-sm font-bold text-forest">{money.format(product.price)}</span>{product.originalPrice && <span className="ml-1 text-xs text-ink/40 line-through">{money.format(product.originalPrice)}</span>}</div><button onClick={() => addItem(product)} className="add-button"><Plus size={15} /> Add</button></div></div></article>
}

function HomePage() {
  const [featured, setFeatured] = useState<Product[]>([])
  useEffect(() => { void catalogRepository.getFeaturedProducts().then(setFeatured) }, [])
  return <>
    <section className="shell pt-5 md:pt-7"><div className="hero-grid overflow-hidden rounded-[24px] bg-forest text-white"><div className="relative z-10 flex min-h-[480px] flex-col justify-end p-7 sm:p-11"><p className="eyebrow text-butter">The new everyday</p><h1 className="hero-title">Find more <em>good things</em><br />for your every day.</h1><p className="mt-5 max-w-sm text-sm leading-6 text-white/75">Objects that bring a little more ease, colour, and care to daily life.</p><Link to="/shop" className="primary-button mt-7">Shop the collection <ArrowRight size={16} /></Link></div><div className="relative min-h-[310px] overflow-hidden"><img className="absolute inset-0 h-full w-full object-cover" src="https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=1400&q=90" alt="A warm, considered home interior" /><div className="absolute inset-0 bg-gradient-to-r from-forest/45 to-transparent" /><div className="absolute bottom-6 right-6 rounded-2xl border border-white/25 bg-forest/70 p-4 text-sm backdrop-blur"><Sparkles size={17} className="mb-5 text-butter" /><p className="text-white/75">Made for a<br />beautifully lived life.</p></div></div></div></section>
    <section className="shell section-space"><SectionTitle eyebrow="Made to be loved" title={<>Current <em>favourites</em></>} link="/shop?featured=true" /><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-4">{featured.slice(0, 4).map((product) => <ProductCard product={product} key={product.id} />)}</div></section>
    <section id="story" className="shell"><div className="relative overflow-hidden rounded-[22px] bg-clay"><img className="h-[420px] w-full object-cover" src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1500&q=85" alt="Calm modern living space" /><div className="absolute inset-0 bg-gradient-to-t from-forest/90 via-forest/10 to-transparent" /><div className="absolute bottom-0 max-w-xl p-7 text-white md:p-10"><p className="eyebrow text-butter">Thoughtfully chosen</p><h2 className="font-display text-4xl leading-none md:text-5xl">The things around us shape how we <em>feel.</em></h2><p className="mt-4 max-w-md text-sm leading-6 text-white/75">From the tools we reach for to the textures we live with, ShopX is a collection of objects worth keeping around.</p></div></div></section>
    <section className="shell grid gap-3 py-8 md:grid-cols-3"><Value icon={<Leaf />} title="Considered finds" text="Thoughtful choices across every category." /><Value icon={<Sparkles />} title="Fresh discoveries" text="New pieces, small delights, all in one place." /><Value icon={<Truck />} title="Easy, always" text="A simple bag today, delivery coming soon." /></section>
    <section className="shell section-space"><SectionTitle eyebrow="ShopX essentials" title={<>Three ways to find your next <em>favourite.</em></>} link="/shop" /><div className="grid gap-3 md:grid-cols-3">{SHOP_CATEGORIES.map((category) => <Link to={`/shop?category=${category.slug}`} className="category-tile group" key={category.slug}><img src={category.image} alt={category.name} /><span style={{ backgroundColor: category.accent }} className="absolute inset-0 opacity-30 mix-blend-multiply" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4 text-white"><p className="text-xs text-white/75">Explore</p><h3 className="font-display text-2xl"><em>{category.name}</em></h3><span className="mt-3 inline-flex rounded-full bg-white px-3 py-1.5 text-[11px] font-semibold text-forest">Shop <ArrowUpRight size={13} className="ml-1" /></span></div></Link>)}</div></section>
    <section className="shell pb-18"><div className="rounded-[22px] bg-butter p-7 text-center md:p-10"><p className="eyebrow">A little note</p><h2 className="mx-auto mt-2 max-w-2xl font-display text-3xl leading-tight text-forest md:text-4xl">The good stuff is closer than you think.</h2><Link to="/shop" className="outline-button mt-6">Explore all products <ArrowRight size={16} /></Link></div></section>
  </>
}

function Value({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="flex items-center gap-4 rounded-[18px] bg-sage/45 p-5"><span className="grid h-10 w-10 place-items-center rounded-full bg-butter text-forest">{icon}</span><div><h3 className="text-sm font-bold text-forest">{title}</h3><p className="mt-1 text-xs text-forest/65">{text}</p></div></div> }

function ShopPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [products, setProducts] = useState<Product[]>([])
  const category = searchParams.get('category') as CategorySlug | null
  const featuredOnly = searchParams.get('featured') === 'true'
  useEffect(() => { void catalogRepository.listProducts({ category: category ?? undefined }).then((all) => setProducts(featuredOnly ? all.filter((item) => item.featured) : all)) }, [category, featuredOnly])
  return <div className="shell section-space"><div className="max-w-2xl"><p className="eyebrow">The collection</p><h1 className="page-title">Objects for a more <em>beautiful</em> everyday.</h1><p className="mt-4 text-sm leading-6 text-ink/60">Explore standout electronics, fashion, and furniture.</p></div><div className="mt-9 flex flex-wrap gap-2"><button onClick={() => setSearchParams({})} className={`filter-pill ${!category && !featuredOnly ? 'active' : ''}`}>All products</button>{SHOP_CATEGORIES.map((item) => <button key={item.slug} onClick={() => setSearchParams({ category: item.slug })} className={`filter-pill ${category === item.slug ? 'active' : ''}`}>{item.name}</button>)}</div><div className="mt-7 flex items-center justify-between"><p className="text-sm text-ink/55">{products.length} finds</p><span className="inline-flex items-center gap-2 text-xs font-semibold text-forest"><SlidersHorizontal size={15} /> Curated selection</span></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4 md:gap-4">{products.map((product) => <ProductCard product={product} key={product.id} />)}</div>{products.length === 0 && <Empty title="No finds in this collection" copy="Try electronics, fashion, furniture, or browse all products." action="Browse all" to="/shop" />}</div>
}

function ProductPage() {
  const { slug } = useParams(); const [product, setProduct] = useState<Product>(); const { addItem } = useCart()
  useEffect(() => { if (slug) void catalogRepository.getProductBySlug(slug).then(setProduct) }, [slug])
  if (!product) return <div className="shell section-space"><Empty title="Product not found" copy="This find may have moved on, but there is plenty more to discover." action="Explore ShopX" to="/shop" /></div>
  return <div className="shell section-space"><Link to="/shop" className="back-link"><ArrowLeft size={16} /> Back to shop</Link><div className="mt-6 grid gap-8 md:grid-cols-2 md:gap-12"><div className="overflow-hidden rounded-[22px] bg-stone"><img className="aspect-square h-full w-full object-cover" src={product.image} alt={product.name} /></div><div className="flex flex-col justify-center"><p className="eyebrow">{product.category}</p><h1 className="page-title mt-2">{product.name}</h1><div className="mt-4 flex items-center gap-2"><span className="flex items-center gap-1 text-sm font-semibold text-forest"><Star size={15} fill="currentColor" /> {product.rating}</span><span className="text-sm text-ink/45">({product.reviews} reviews)</span></div><p className="mt-6 max-w-md text-sm leading-7 text-ink/65">{product.description}</p><div className="mt-6 flex gap-2">{product.colors.map((color) => <span key={color} style={{ backgroundColor: color }} className="h-7 w-7 rounded-full border-2 border-white ring-1 ring-ink/15" />)}</div><p className="mt-8 text-2xl font-bold text-forest">{money.format(product.price)}</p><button onClick={() => addItem(product)} className="primary-button mt-5 w-fit">Add to bag <ShoppingBag size={16} /></button><p className="mt-5 flex items-center gap-2 text-xs text-ink/55"><Check size={15} className="text-forest" /> Carefully selected for the ShopX collection</p></div></div></div>
}

function SearchPage() { const [params] = useSearchParams(); const query = params.get('q') ?? ''; const [results, setResults] = useState<Product[]>([]); useEffect(() => { void catalogRepository.listProducts({ query }).then(setResults) }, [query]); return <div className="shell section-space"><p className="eyebrow">Search results</p><h1 className="page-title">Results for <em>“{query}”</em></h1><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4 md:gap-4">{results.map((product) => <ProductCard product={product} key={product.id} />)}</div>{results.length === 0 && <Empty title="Nothing quite matches" copy="Try a different word or explore one of our curated categories." action="Browse categories" to="/categories" />}</div> }

function CartPage() { const { items, updateQuantity, removeItem } = useCart(); if (!items.length) return <div className="shell section-space"><Empty title="Your bag is waiting" copy="Add the things that make your day a little better." action="Start shopping" to="/shop" /></div>; return <div className="shell section-space"><p className="eyebrow">Your selection</p><h1 className="page-title">Your <em>bag.</em></h1><div className="mt-8 grid gap-8 lg:grid-cols-[1.5fr_.8fr]"><div className="divide-y divide-ink/10 border-y border-ink/10">{items.map(({ product, quantity }) => <div className="flex gap-4 py-5" key={product.id}><img src={product.image} alt="" className="h-24 w-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><Link className="font-semibold text-ink" to={`/products/${product.slug}`}>{product.name}</Link><p className="mt-1 text-sm font-semibold text-forest">{money.format(product.price)}</p><div className="mt-4 flex items-center justify-between"><div className="quantity"><button aria-label="Decrease quantity" onClick={() => updateQuantity(product.id, quantity - 1)}><Minus size={14} /></button><span>{quantity}</span><button aria-label="Increase quantity" onClick={() => updateQuantity(product.id, quantity + 1)}><Plus size={14} /></button></div><button onClick={() => removeItem(product.id)} className="text-ink/45 hover:text-terracotta" aria-label={`Remove ${product.name}`}><Trash2 size={17} /></button></div></div></div>)}</div><CheckoutPanel /></div></div> }

function Empty({ title, copy, action, to }: { title: string; copy: string; action: string; to: string }) { return <div className="mt-8 grid min-h-[260px] place-items-center rounded-[20px] bg-sand p-8 text-center"><div><Search className="mx-auto text-forest/55" /><h2 className="mt-4 font-display text-3xl text-forest">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-ink/60">{copy}</p><Link to={to} className="outline-button mt-5">{action} <ArrowRight size={16} /></Link></div></div> }

export default function App() { return <Shell><Routes><Route path="/" element={<HomePage />} /><Route path="/shop" element={<ShopPage />} /><Route path="/products/:slug" element={<ProductPage />} /><Route path="/search" element={<SearchPage />} /><Route path="/cart" element={<CartPage />} /><Route path="/account" element={<AccountPage />} /><Route path="/profile" element={<ProfilePage />} /><Route path="/admin" element={<AdminPage />} /><Route path="*" element={<HomePage />} /></Routes></Shell> }
